from fpdf import FPDF
import datetime


def generate_pdf(username, glucose, bmi, age, blood_pressure, insulin, risk, result, explanation):
    pdf = FPDF()
    pdf.add_font("DejaVu", "", "fonts/DejaVuSans.ttf")
    pdf.add_font("DejaVu", "B", "fonts/DejaVuSans-Bold.ttf")
    pdf.add_page()

    # ===== HEADER =====
    pdf.set_fill_color(25, 118, 210)
    pdf.rect(0, 0, 210, 35, 'F')

    pdf.set_text_color(255, 255, 255)
    pdf.set_font("DejaVu", "B", 22)
    pdf.set_y(8)
    pdf.cell(0, 10, "AI Healthcare System", align="C", ln=True)

    pdf.set_font("DejaVu", "", 12)
    pdf.cell(0, 8, "Diabetes Prediction Report", align="C", ln=True)

    # ===== THÔNG TIN =====
    pdf.set_text_color(0, 0, 0)
    pdf.set_y(45)
    pdf.set_font("DejaVu", "", 11)
    pdf.cell(0, 8, f"Patient: {username}", ln=True)
    pdf.cell(0, 8, f"Date: {datetime.datetime.now().strftime('%d/%m/%Y %H:%M')}", ln=True)

    pdf.ln(5)

    # ===== KẾT QUẢ =====
    pdf.set_fill_color(25, 118, 210)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("DejaVu", "B", 13)
    pdf.cell(0, 10, "  Prediction Result", ln=True, fill=True)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("DejaVu", "", 11)
    pdf.ln(3)

    if risk > 50:
        pdf.set_text_color(200, 0, 0)
    else:
        pdf.set_text_color(0, 150, 0)
    pdf.set_font("DejaVu", "B", 14)
    pdf.cell(0, 10, f"  Diabetes Risk: {risk:.2f}%  -  {result}", ln=True)

    pdf.ln(3)

    # ===== CHỈ SỐ =====
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(25, 118, 210)
    pdf.set_font("DejaVu", "B", 13)
    pdf.cell(0, 10, "  Health Indicators", ln=True, fill=True)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("DejaVu", "", 11)
    pdf.ln(3)

    indicators = [
        ("Glucose", glucose, 100, "mg/dL"),
        ("Blood Pressure", blood_pressure, 80, "mmHg"),
        ("BMI", bmi, 24.9, ""),
        ("Insulin", insulin, 85, "uU/mL"),
        ("Age", age, "-", "years"),
    ]

    for name, value, normal, unit in indicators:
        pdf.set_fill_color(240, 248, 255)
        pdf.cell(95, 9, f"  {name}: {value} {unit}", border=1, fill=True)
        pdf.cell(95, 9, f"  Normal: {normal} {unit}", border=1, fill=False, ln=True)

    pdf.ln(5)

    # ===== AI GIẢI THÍCH =====
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(25, 118, 210)
    pdf.set_font("DejaVu", "B", 13)
    pdf.cell(0, 10, "  AI Analysis", ln=True, fill=True)

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("DejaVu", "", 10)
    pdf.ln(3)
    clean = explanation.replace("**", "")
    pdf.multi_cell(0, 7, clean)

    pdf.ln(5)

    # ===== FOOTER =====
    pdf.set_y(-20)
    pdf.set_fill_color(25, 118, 210)
    pdf.rect(0, pdf.get_y(), 210, 20, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("DejaVu", "", 9)
    pdf.cell(0, 10, "Generated by AI Healthcare System  |  For medical reference only", align="C")

    return bytes(pdf.output())